### ISSUE TITLE
Make generator run in parallel

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow-incubator/snowplow-event-generator#17]
Existing implementation doesn't make use of parallelism in any step, we should make use of multiple cores.

**Comment by voropaevp** [comment]
it is parallel
<img width="1744" alt="image" src="https://user-images.githubusercontent.com/7419380/157956880-ca0e0a1a-5326-4a08-848a-bd7aee26f4ed.png">

**Comment by oguzhanunlu** [comment]
Thanks for the correction Pavel. I found generator slow when I last used it and opened this after not seeing any par* usage within the codebase. Clearly cats-effect makes it run in parallel to some degree and I didn't check it back then. However I still think we can make it faster.
